### ISSUE TITLE
wrong size of data type in qsort

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [clouren/SPEX#2]
@emc2git @clouren @LoreMD :  I found the bug that was causing SPEX 3.0 to fail on 32-bit systems.

https://github.com/clouren/SPEX/blob/1eaa6c79412d8efa9de76598344ea4d2c11be06a/SPEX/SPEX_Cholesky/Source/spex_cholesky_up_triangular_solve.c#L109

That's  bug.  It should have `sizeof (int64_t)` not `sizeof (int64_t *)`.  On a 64-bit system, those are the same values.  The data is sizeof(int64_t), which is 8.  But on a 32-bit system, the pointer has a size of 4 bytes.

There are other issues and the 32-bit builds are still failing, but this at least fixed one of them.  I'll fix this in v3.1.

**Comment by DrTimothyAldenDavis** [comment]
Another related bug:  this too should be `sizeof (int64_t)` not `sizeof (int64_t *)`:

https://github.com/clouren/SPEX/blob/1eaa6c79412d8efa9de76598344ea4d2c11be06a/SPEX/SPEX_Cholesky/Source/spex_cholesky_symbolic_analysis.c#L81

**Comment by emc2git** [comment]
Wow, that was a nice catch Tim.
But that is in addition to the main mystery of bitcn. We talked to Chris,
and we can all discuss next Monday; hopefully altogether can figure that
one out.

**Comment by emc2git** [comment]
Yikes, I wonder why/how all those happened, it would rarely make sense to
ask for sizeof (uint64_t *)...
Lore and/or Chris, any ideas?

**Comment by DrTimothyAldenDavis** [comment]
The `mp_bitcnt_t` is easy to understand.  It's spurious.

With these 2 bugs above, SPEX 3.0 fails on any system with 32-bit pointers.  The `mp_bitcnt_t` is 32 bits on all 32-bit platforms, plus more systems (like 64-bit Windows).

So the test in `SPEX_initialize` where it refused to initialize SPEX if `sizeof (mp_bitcnt_t) < sizeof (int64_t)` was just hiding these 2 bugs.  It simply avoiding running on any 32-bit system, and other systems that had 64-bit pointers.

When I took out the `sizeof (mp_bitcnt_t) < sizeof (int64_t)` test, the 64-bit Windows systems worked just fine.  Only the 32-bit systems (Windows and Linux) failed.

**Comment by DrTimothyAldenDavis** [comment]
> Yikes, I wonder why/how all those happened, it would rarely make sense to ask for sizeof (uint64_t *)... Lore and/or Chris, any ideas?

It's a simple typo.  The output of malloc of an array of int64_t values (say) would be typecast to (int64_t *) with the star.  The sizeof should be sizeof (int64_t) without the star.  I think it's a simple cut-and-paste kind of mistake.

**Comment by DrTimothyAldenDavis** [comment]
I think this fixes the 32-bit bug in SPEX 3.0.

The 32-bit builds pass in this test:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/7981497164
(see the mingw (MINGW32) and mingw (CLANG32) tests).

The other test that was failing was the alpine (x86) and I think another one in this test, which hasn't run yet because another run is still going with debug enabled:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/7981495419

But I'm guessing that will succeed. Assuming that's the case,  SPEX 3.1 will now run on any Windows, Linux, or Mac system, either 32-bit or 64-bit.  The `mp_bitcnt_t` test in SPEX_initialize has been removed in my
spexdev2 branch of SuiteSparse:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/68e59ad2fa303f0c2f824307e8a429e9304a240e/SPEX/SPEX_Utilities/Source/SPEX_initialize.c#L39-L62

which used to have this test, now deleted:
https://github.com/clouren/SPEX/blob/1eaa6c79412d8efa9de76598344ea4d2c11be06a/SPEX/SPEX_Utilities/Source/SPEX_initialize.c#L43-L44

**Comment by emc2git** [comment]
That was also my line of thinking: " It's a simple typo. [...] I think it's
a simple cut-and-paste kind of mistake. ", but I just wanted to make sure.

Wow, this is amazing, Tim; thanks very much for the effort in this regard!

I'm still curious about the motivation behind the " mp_bitcnt_t check "
because of the way it was commented: "GMP requires..."; given that comment,
I don't think that check was added simply to avoid the crashes on 32-bit
systems. Regardless, if the tests pass, that is really all that matters.

**Comment by DrTimothyAldenDavis** [comment]
I think we added it because of the crashes on 32-bit systems.  We thought it was because the mp_bitcnt_t was different and it occurred when the crash happened, and then adding the test made the crash go away.  It was a spurious correlation though.

**Comment by DrTimothyAldenDavis** [comment]
The tests are all passing now.

**Comment by emc2git** [comment]
Sounds convincing enough to me :)

*Erick Moreno-Centeno*

Associate Professor and Mike & Sugar Barnes Faculty Fellow
Wm Michael Barnes '64 Department of Industrial and Systems Engineering

Texas A&M University

ph: (979) 458-2335 | ***@***.***
– – – – – – – – – – – – – – – – – – – – – – – –
www.tamu.edu

**Comment by emc2git** [comment]
Yay!

😃

*Erick Moreno-Centeno*

Associate Professor and Mike & Sugar Barnes Faculty Fellow
Wm Michael Barnes '64 Department of Industrial and Systems Engineering

Texas A&M University

ph: (979) 458-2335 | ***@***.***
– – – – – – – – – – – – – – – – – – – – – – – –
www.tamu.edu
